import matplotlib.pyplot as plt
import numpy as np
from PIL import Image
from numpy.fft import fft2, fftshift, ifft2, ifftshift
from matplotlib.patches import Rectangle

MIN_VALUE = 1e-10


def extent_func(img):
    """Calculate extent for imshow with centered coordinates."""
    rows, cols = img.shape
    return (-cols // 2, cols // 2, -rows // 2, rows // 2)


def calculate_harmonic_periods(img_shape, pixel_size, pattern_period):
    """Calculate and adjust harmonic periods."""
    vert_harm = int((pixel_size[0] * img_shape[0]) / pattern_period)
    hor_harm = int((pixel_size[1] * img_shape[1]) / pattern_period)

    # # # Ensure even numbers
    # vert_harm += (vert_harm % 2) + 1
    # hor_harm += (hor_harm % 2) + 1
    # # print("vert_harm", vert_harm)
    # # print("hor_harm", hor_harm)
    # print("Theoretical harmonic periods(H/V):", (hor_harm, vert_harm))
    return [vert_harm, hor_harm]


def calculate_peak_index(har_v, har_h, n_rows, n_columns, period_vert, period_hor):
    """
    Calculate the theoretical peak index(in pixel) for harmonic [har_v, har_h].
    Explain:
    1. n_rows // 2 and n_columns // 2 represent the center of the image.
    2. har_v, har_h is the harmonic index or the order of the harmonic.
    For instance, har_v = 1,har_v = 0 means the first harmonic in the vertical direction, and the zeroth harmonic in the
    horizontal direction.
    3. period_vert and period_hor is the period of the basic frequency in the harmonic.
    """
    results = [n_rows // 2 + har_v * period_vert, n_columns // 2 + har_h * period_hor]
    # print("the theoretical peak index is:", results)
    return results


def find_peak_in_region(img_fft, theoretical_idx, search_region):
    """
    Find the factual harmonic peak index(in pixel) for harmonic through the search region in experimental data.
    Explain:
    1. img_fft is the Fourier transform of the image.
    2. theoretical_idx is the theoretical peak index. It is generated by calculate_peak_index.[v-row,h-column].
    3. search_region is the search region around the theoretical index to find the peak.
    4. the mask is full-zero except for the search region, which is full-one.To find the peak in the search region.
    5. np.where will return two one-dimensional arrays, first array-the row index, second array-the column index.
    """
    intensity = np.abs(img_fft)
    n_rows, n_columns = img_fft.shape
    mask = np.zeros((n_rows, n_columns))

    i, j = theoretical_idx
    # print("i,j", i, j)
    # print("search_region", search_region)
    mask[
        i - search_region[0] : i + search_region[0],
        j - search_region[1] : j + search_region[1],
    ] = 1

    masked_intensity = intensity * mask
    max_idx = np.unravel_index(np.argmax(masked_intensity), masked_intensity.shape)
    return list(max_idx)


def calculate_contrast(
    img,
    pixel_size,
    g_period,
    source_dist,
    det2sample,
    search_region=None,
    use_theoretical_peak=True,
    plot_flag=False,
    save_path=None,
    verbose=False,
):
    """
    Calculate the peak positions of the 00, 01, and 10 harmonics, and use them
    to compute accurate harmonic periods.

    Args:
        img (ndarray): Input image.
        initial_period (list, optional): Initial harmonic period estimate
            [period_vert, period_hor]. If None, it is detected automatically.
        search_region (int/list): Peak search region size. It can be an integer
            or [vertical_search_range, horizontal_search_range].
        plot_flag (bool): Whether to display the visualization.
        save_path (str, optional): Path to save the visualization.

    Returns:
        tuple: (
            accurate_period: [period_vert, period_hor], the accurate harmonic period,
            peak_positions: {'00': [y0, x0], '01': [y01, x01], '10': [y10, x10]},
            the peak positions of each harmonic
        )
    """
    # TODO: Convert parameters
    pattern_period = g_period * (det2sample + source_dist) / source_dist
    pixel_size = [pixel_size, pixel_size]
    init_periods = calculate_harmonic_periods(img.shape, pixel_size, pattern_period)

    # 1. Apply Window Function to reduce spectral leakage
    n_rows, n_columns = img.shape

    # Apply circular Gaussian window to reduce spectral leakage
    y_coords = np.linspace(-1, 1, n_rows)
    x_coords = np.linspace(-1, 1, n_columns)
    xx, yy = np.meshgrid(x_coords, y_coords)
    r = np.sqrt(xx**2 + yy**2)
    sigma = 0.5  # Gaussian sigma (controls window width)
    window_2d = np.exp(-(r**2) / (2 * sigma**2))

    # Apply window to image
    img_windowed = img * window_2d

    # 2. Calculate FFT
    img_fft = fftshift(fft2(img_windowed, norm="ortho"))

    period_vert, period_hor = init_periods

    # Set the search region
    if search_region is None:
        search_region = [max(10, int(min(period_vert, period_hor) // 4))] * 2
    elif isinstance(search_region, int):
        search_region = [search_region] * 2

    # 3. Calculate theoretical peak positions for contrast calculation
    theoretical_peak_positions = {}

    # 3.1 Calculate the theoretical position of the 00 harmonic (center peak)
    idx_peak_00 = calculate_peak_index(0, 0, n_rows, n_columns, period_vert, period_hor)
    theoretical_peak_positions["00"] = [int(idx_peak_00[0]), int(idx_peak_00[1])]

    # 3.2 Calculate the theoretical position of the 01 harmonic (first horizontal harmonic)
    idx_peak_01 = calculate_peak_index(0, 1, n_rows, n_columns, period_vert, period_hor)
    theoretical_peak_positions["01"] = [int(idx_peak_01[0]), int(idx_peak_01[1])]

    # 3.3 Calculate the theoretical position of the 10 harmonic (first vertical harmonic)
    idx_peak_10 = calculate_peak_index(1, 0, n_rows, n_columns, period_vert, period_hor)
    theoretical_peak_positions["10"] = [int(idx_peak_10[0]), int(idx_peak_10[1])]

    # 4. Find experimental peak positions for validation and visualization
    experimental_peak_positions = {}
    peak_00_exp = find_peak_in_region(img_fft, idx_peak_00, search_region)
    experimental_peak_positions["00"] = peak_00_exp

    peak_01_exp = find_peak_in_region(img_fft, idx_peak_01, search_region)
    experimental_peak_positions["01"] = peak_01_exp

    peak_10_exp = find_peak_in_region(img_fft, idx_peak_10, search_region)
    experimental_peak_positions["10"] = peak_10_exp

    # 6. Extract harmonic region and calculate spatial intensity
    def extract_harmonic_region_intensity(fft_data, peak_pos, period_vert, period_hor):
        """
        Extract harmonic region, perform IFFT, and calculate mean spatial intensity.

        Args:
            fft_data: FFT spectrum data
            peak_pos: Peak position [y, x]
            period_vert: Vertical harmonic period (pixels)
            period_hor: Horizontal harmonic period (pixels)

        Returns:
            Mean intensity (amplitude) in spatial domain
        """
        y_peak, x_peak = peak_pos

        # Determine window size (half of harmonic period)
        half_window_vert = int(period_vert // 2)
        half_window_hor = int(period_hor // 2)

        # Calculate region boundaries
        n_rows, n_columns = fft_data.shape
        y_start = max(0, y_peak - half_window_vert)
        y_end = min(n_rows, y_peak + half_window_vert)
        x_start = max(0, x_peak - half_window_hor)
        x_end = min(n_columns, x_peak + half_window_hor)

        # Extract region
        region = fft_data[y_start:y_end, x_start:x_end]

        # IFFT to spatial domain
        # Use ifftshift to move the centered peak to the origin (0,0) before IFFT
        spatial_domain = ifft2(ifftshift(region))

        # Calculate mean intensity (amplitude)
        # Note: This corresponds to the amplitude of the harmonic component
        mean_intensity = np.mean(np.abs(spatial_domain))

        return mean_intensity

    # Select theoretical or experimental peak positions based on the parameter
    if use_theoretical_peak:
        peak_positions_for_contrast = theoretical_peak_positions
        peak_type = "Theoretical"
    else:
        peak_positions_for_contrast = {
            "00": experimental_peak_positions["00"],
            "01": experimental_peak_positions["01"],
            "10": experimental_peak_positions["10"],
        }
        peak_type = "Experimental"

    # Extract harmonic region intensity using the selected peak positions and theoretical periods
    I_00 = extract_harmonic_region_intensity(
        img_fft, peak_positions_for_contrast["00"], period_vert, period_hor
    )
    I_01 = extract_harmonic_region_intensity(
        img_fft, peak_positions_for_contrast["01"], period_vert, period_hor
    )
    I_10 = extract_harmonic_region_intensity(
        img_fft, peak_positions_for_contrast["10"], period_vert, period_hor
    )

    # Calculate contrast
    contrast01 = 2 * I_01 / I_00
    contrast10 = 2 * I_10 / I_00
    contrast = (contrast01 + contrast10) / 2

    # Calculate harmonic region boundaries (fixed size for all harmonics)
    half_window_vert = int(period_vert // 2)
    half_window_hor = int(period_hor // 2)

    # 7. Visualization (Plot harmonic regions with rectangles)
    if plot_flag:
        fig, ax = plt.subplots(figsize=(12, 10))

        # Plot FFT spectrum
        im = ax.imshow(
            np.log10(np.abs(img_fft) + MIN_VALUE),
            cmap="inferno",
            interpolation="nearest",
            extent=extent_func(img_fft),
        )

        # Define colors for different harmonics
        colors = {"00": "white", "01": "cyan", "10": "yellow"}

        # Loop through harmonics to plot regions and peaks
        for harmonic in ["00", "01", "10"]:
            peak_pos = peak_positions_for_contrast[harmonic]
            y_peak, x_peak = int(peak_pos[0]), int(peak_pos[1])

            y_start = max(0, y_peak - half_window_vert)
            y_end = min(n_rows, y_peak + half_window_vert)
            x_start = max(0, x_peak - half_window_hor)
            x_end = min(n_columns, x_peak + half_window_hor)

            # Draw harmonic extraction region rectangle
            rect_width = x_end - x_start
            rect_height = y_end - y_start

            # Convert to centered coordinates for plotting
            rect_x = x_start - n_columns // 2
            rect_y = n_rows // 2 - y_end

            rect = Rectangle(
                (rect_x, rect_y),
                rect_width,
                rect_height,
                linewidth=2,
                edgecolor=colors[harmonic],
                facecolor="none",
                linestyle="--",
                label=f"Region {harmonic}",
            )
            ax.add_patch(rect)

            # Mark peak position
            ax.scatter(
                x_peak - n_columns // 2,
                n_rows // 2 - y_peak,
                color=colors[harmonic],
                marker="x",
                s=150,
                linewidths=2,
                label=f"Peak {harmonic}",
            )

        ax.set_title(
            f"Harmonic Analysis | Peak Type: {peak_type} | Contrast = {contrast:.4f}",
            fontsize=14,
            weight="bold",
        )
        ax.set_xlabel("Horizontal [pixels]")
        ax.set_ylabel("Vertical [pixels]")
        ax.legend(loc="upper right", fontsize=10, framealpha=0.8)
        ax.grid(True, alpha=0.3)

        # Add colorbar
        plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04).set_label(
            "Log10 Magnitude", rotation=270, labelpad=20
        )

        plt.tight_layout()

        if save_path:
            plt.savefig(save_path, dpi=300, bbox_inches="tight")
            if verbose:
                print(f"Contrast analysis plot saved to {save_path}")

        plt.show()

    # 8. Print detailed information
    if verbose:
        print("\n" + "=" * 70)
        print(f"Peak Type Used for Contrast Calculation: {peak_type}")
        print("\nSelected Peak Positions:")
        for h in ["00", "01", "10"]:
            print(f"  {h}: {peak_positions_for_contrast[h]}")

        print(
            f"\nTheoretical Harmonic Periods (H/V): ({period_hor:.2f}, {period_vert:.2f}) pixels"
        )
        print(
            f"Harmonic Extraction Region Size: {half_window_vert * 2} x {half_window_hor * 2} pixels"
        )
        print("\nContrast Results:")
        print(f"  Contrast (01): {contrast01:.4f}")
        print(f"  Contrast (10): {contrast10:.4f}")
        print(f"  Average Contrast: {contrast:.4f}")
        print("=" * 70 + "\n")

    return contrast


if __name__ == "__main__":
    image_path = "/Users/guanzhh/Vscode_worksapce/wavefront-sim/result/20251201/zernike_aberration_scan/labels/j6_c0.tif"
    img = Image.open(image_path)
    img = np.array(img).astype(np.uint16)

    det2source = 0.465
    source_dist = 0.0129
    det2sample = det2source - source_dist
    pixel_size = 3.25e-06
    g_period = 3.0e-6 / np.sqrt(2)

    contrast = calculate_contrast(
        img,
        pixel_size,
        g_period,
        source_dist,
        det2sample,
        search_region=None,
        plot_flag=True,
        save_path=None,
        verbose=True,
    )
    print(contrast)
