import matplotlib.pyplot as plt
import numpy as np
from numpy.fft import fft2, fftshift


def calculate_harmonic_periods(img_shape, pixel_size, pattern_period):
    """Calculate and adjust harmonic periods."""
    vert_harm = int((pixel_size[0] * img_shape[0]) / pattern_period)
    hor_harm = int((pixel_size[1] * img_shape[1]) / pattern_period)

    # # # Ensure even numbers
    # vert_harm += (vert_harm % 2) + 1
    # hor_harm += (hor_harm % 2) + 1
    # # print("vert_harm", vert_harm)
    # # print("hor_harm", hor_harm)

    return [vert_harm, hor_harm]


def calculate_peak_index(har_v, har_h, n_rows, n_columns, period_vert, period_hor):
    """
    Calculate the theoretical peak index(in pixel) for harmonic [har_v, har_h].
    Explain:
    1. ``n_rows // 2`` and ``n_columns // 2`` represent the image center.
    2. har_v, har_h is the harmonic index or the order of the harmonic.
    For instance, har_v = 1,har_v = 0 means the first harmonic in the vertical direction, and the zeroth harmonic in the
    horizontal direction.
    3. period_vert and period_hor is the period of the basic frequency in the harmonic.
    """
    results = [n_rows // 2 + har_v * period_vert, n_columns // 2 + har_h * period_hor]
    # print("the theoretical peak index is:", results)
    return results


def find_peak_in_region(img_fft, theoretical_idx, search_region):
    """
    Find the factual harmonic peak index(in pixel) for harmonic through the search region in experimental data.
    Explain:
    1. img_fft is the Fourier transform of the image.
    2. theoretical_idx is the theoretical peak index. It is generated by calculate_peak_index.[v-row,h-column].
    3. search_region is the search region around the theoretical index to find the peak.
    4. the mask is full-zero except for the search region, which is full-one.To find the peak in the search region.
    5. np.where will return two one-dimensional arrays, first array-the row index, second array-the column index.
    """
    intensity = np.abs(img_fft)
    n_rows, n_columns = img_fft.shape
    mask = np.zeros((n_rows, n_columns))

    i, j = theoretical_idx
    # print("i,j", i, j)
    # print("search_region", search_region)
    mask[
        i - search_region[0] : i + search_region[0],
        j - search_region[1] : j + search_region[1],
    ] = 1

    masked_intensity = intensity * mask
    max_idx = np.unravel_index(np.argmax(masked_intensity), masked_intensity.shape)
    return list(max_idx)


def calculate_contrast(
    img: np.ndarray,
    pixel_size: list[float],
    g_period: float,
    source_dist: float,
    det2sample: float,
    search_region: int | list[int] | None = None,
    plot_flag: bool = False,
) -> float:
    """
    Locate the 00 and 01 harmonic peaks and compute the grating fringe contrast.

    Args:
        img (ndarray): Input image.
        pixel_size (list[float]): Detector pixel size [vert, hor] in meters (m).
        g_period (float): Grating period in meters (m).
        source_dist (float): Source-to-grating distance in meters (m).
        det2sample (float): Detector-to-sample distance in meters (m).
        search_region (int or list[int], optional): Peak-search region size,
            either an integer or ``[vertical_range, horizontal_range]``.
        plot_flag (bool): Whether to display the visualization.

    Returns:
        float: Visibility/contrast value of the grating fringes.
    """
    # TODO: normalize the input parameter conventions
    pattern_period = g_period * (det2sample + source_dist) / source_dist
    # pixel_size = [pixel_size, pixel_size]
    init_periods = calculate_harmonic_periods(img.shape, pixel_size, pattern_period)

    # 1. Compute the image FFT
    n_rows, n_columns = img.shape
    img_fft = fftshift(fft2(img, norm="ortho"))

    period_vert, period_hor = init_periods

    # Configure the search region
    if search_region is None:
        search_region = [max(10, int(min(period_vert, period_hor) // 2))] * 2
    elif isinstance(search_region, int):
        search_region = [search_region] * 2

    # 3. Locate the three harmonic peaks accurately
    peak_positions = {}

    # 3.1 00 harmonic (center peak)
    idx_peak_00 = calculate_peak_index(0, 0, n_rows, n_columns, period_vert, period_hor)
    peak_00 = find_peak_in_region(img_fft, idx_peak_00, search_region)
    peak_positions["00"] = peak_00

    # 3.2 01 harmonic (first horizontal harmonic)
    idx_peak_01 = calculate_peak_index(0, 1, n_rows, n_columns, period_vert, period_hor)
    peak_01 = find_peak_in_region(img_fft, idx_peak_01, search_region)
    peak_positions["01"] = peak_01

    # 3.3 10 harmonic (first vertical harmonic)
    idx_peak_10 = calculate_peak_index(1, 0, n_rows, n_columns, period_vert, period_hor)
    peak_10 = find_peak_in_region(img_fft, idx_peak_10, search_region)
    peak_positions["10"] = peak_10

    # 4. Compute the harmonic periods from the peak positions
    # Horizontal period = horizontal distance between the 01 and 00 peaks
    exp_period_h = abs(peak_01[1] - peak_00[1])
    # Vertical period = vertical distance between the 10 and 00 peaks
    exp_period_v = abs(peak_10[0] - peak_00[0])
    # TODO: Decide whether to use peak-to-peak distances or the theoretical
    # harmonic period after localizing the harmonic peaks.
    # exp_period_v = init_periods[1]
    # exp_period_h = init_periods[0]

    # Compute self-imaging contrast using the harmonic peak values
    contrast01 = (
        2
        * np.abs(img_fft[peak_01[0], peak_01[1]])
        / np.abs(img_fft[peak_00[0], peak_00[1]])
    )
    contrast10 = (
        2
        * np.abs(img_fft[peak_10[0], peak_10[1]])
        / np.abs(img_fft[peak_00[0], peak_00[1]])
    )
    contrast = (contrast01 + contrast10) / 2
    print("contrast01:", contrast01)
    print("contrast10:", contrast10)
    print("contrast:", contrast)

    # 5. Visualize the result
    if plot_flag:
        plt.figure(figsize=(10, 8))
        plt.imshow(np.log10(np.abs(img_fft)), cmap="inferno")

        # Mark the 00 peak
        plt.scatter(
            peak_00[1], peak_00[0], color="white", marker="+", s=150, label="00 Peak"
        )

        # Mark the 01 peak
        plt.scatter(
            peak_01[1], peak_01[0], color="cyan", marker="+", s=150, label="01 Peak"
        )

        # Mark the 10 peak
        plt.scatter(
            peak_10[1], peak_10[0], color="yellow", marker="+", s=150, label="10 Peak"
        )

        # Connecting lines
        plt.plot(
            [peak_00[1], peak_01[1]],
            [peak_00[0], peak_01[0]],
            "c--",
            alpha=0.7,
            label=f"Horizontal Period: {exp_period_h:.2f}",
        )

        plt.plot(
            [peak_00[1], peak_10[1]],
            [peak_00[0], peak_10[0]],
            "y--",
            alpha=0.7,
            label=f"Vertical Period: {exp_period_v:.2f}",
        )

        plt.title("Harmonic Peaks and Accurate Periods")
        plt.colorbar(label="Log10 Magnitude")
        plt.legend()
        plt.grid(True, alpha=0.3)
        plt.show()

        # Print summary information
        print(f"00 Peak position: {peak_00}")
        print(f"01 Peak position: {peak_01}")
        print(f"10 Peak position: {peak_10}")
        print(f"Accurate horizontal period: {exp_period_h:.2f} pixels")
        print(f"Accurate vertical period: {exp_period_v:.2f} pixels")

    return contrast
